# Generated by Django 4.2.4 on 2023-09-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_orderposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
